Colorpicker
GitMozzarella/FiguresApp pull request #1
Opened 2023-09-20 20:18 UTC by GitMozzarella

2023-09-20 21:15 UTC, bezvrednyy requested changes

2023-09-20 21:15 UTC, iakovalgaev commented on .prettierrc
> +    "tabWidth": 4,
Визуально тяжело воспринимается код с четырями пробелами _(скриншоты кидал в телеграмме до этого)_. Мне кажется лучше уменьшить, чтобы когда кто-то просматривал твой репозиторий, ему было комфортно.

2023-09-20 21:15 UTC, iakovalgaev commented on src/App.css
> +    border-right: 5px solid#818181;
Цвет можно вынести в `border-color`. А остальные свойства оформить в виде `border: 1px 5px`

2023-09-20 21:15 UTC, iakovalgaev commented on src/App.jsx
> +    const initialFigures = JSON.parse(localStorage.getItem('figures'));
Строковое значение-ключ нужно вынести в переменную _(и скорее всего экспортнуть, ведь в другом месе ты где-то используешь setItem)_. Нужно вынести в константу, чтобы в случае необходимости переименования ключа не нужно было вносить изменения в двух местах

2023-09-20 21:15 UTC, iakovalgaev commented on src/App.jsx
> +    const [fillColor, setFillColor] = useState('#353535');
Аналогично, "магическое значение" нужно вынести в константу

2023-09-20 21:15 UTC, iakovalgaev commented on src/App.jsx
> +        initialFigures ? initialFigures : [],
В initialFigures лежит значение из localStarage. А что если кто-то в LS под ключ 'figures' запишет просто цифру 5? Тогда у тебя состояние `figures` проинициализирует неккореткно.

Поэтому, как минимум, нужно проверить, что initialFigures это массив. Для этого используют `Array.isArray()`.

2023-09-20 21:15 UTC, bezvrednyy commented on src/App.jsx
> +    const addFigures = (type) => {
Попробуй создать две фигуры. Потом удалить первую и создать новую. А после выделить только одну из двух _(должна появится проблема и тебе нужно разобраться почему так)_

2023-09-20 21:15 UTC, bezvrednyy commented on src/App.jsx
> +    };
Лишняя обёртка функции

2023-09-20 21:15 UTC, bezvrednyy commented on src/App.jsx
> +        });
Можно оформить лаконичнее: 
```
setFigures((figures) => figures.map((x) => x.id === selectedFigures
    ? { ...x, color: fillColor }
    : x;
));
```

2023-09-20 21:15 UTC, bezvrednyy commented on src/App.jsx
> +        localStorage.setItem('figures', JSON.stringify(figures));
Заиспользовать константу

2023-09-20 21:15 UTC, bezvrednyy commented on src/components/AppMenu.jsx
> +                        onClick={() => addFigures(0)}
Здесь и ниже что за магические цифры? Тоже вынести их в константы. А лучше вынести в константы и цифры заменить на говорящие строки, аля "triangle" и "rectangle"

2023-09-20 21:15 UTC, bezvrednyy commented on src/components/Workspace.jsx
> +                }
Ветвистая штука получается. Конструкцию if else не очень смотрится в JSX. Обычно это сигнал разбить код на компоненты и заиспользовать тернарный оператор.

2023-09-22 20:16 UTC, GitMozzarella commented on .prettierrc
> +    "tabWidth": 4,
сделал.да у меня раньше неправильно подключал Prettier

2023-09-22 20:16 UTC, GitMozzarella commented on src/App.css
> +    border-right: 5px solid#818181;
точно )можно было уменьшить в 2 строчки.сделал

2023-09-22 20:17 UTC, GitMozzarella commented on src/App.jsx
> +    const initialFigures = JSON.parse(localStorage.getItem('figures'));
да создал const itemLC

2023-09-22 20:17 UTC, GitMozzarella commented on src/App.jsx
> +    const [fillColor, setFillColor] = useState('#353535');
вынес строкое значение цвета в const

2023-09-22 21:16 UTC, GitMozzarella commented on src/App.jsx
> +        initialFigures ? initialFigures : [],
сделано

2023-09-22 21:17 UTC, GitMozzarella commented on src/App.jsx
> +    };
так точно убрал

2023-09-22 21:31 UTC, GitMozzarella commented on src/App.jsx
> +        });
"ниндзя код " так сказать))

2023-09-22 21:31 UTC, GitMozzarella commented on src/App.jsx
> +        localStorage.setItem('figures', JSON.stringify(figures));
да сделал get и set

2023-09-22 21:32 UTC, GitMozzarella commented on src/components/AppMenu.jsx
> +                        onClick={() => addFigures(0)}
сделано

2023-09-22 22:06 UTC, GitMozzarella commented on src/components/Workspace.jsx
> +                }
вынес в подпапку 2 компонента  и использовал тернарник

2023-09-22 23:38 UTC, GitMozzarella commented on src/App.jsx
> +    const addFigures = (type) => {
да проблема в дублировании id в localstorage, попробую переделать .

2023-09-27 00:03 UTC, GitMozzarella commented on src/App.jsx
> +    const addFigures = (type) => {
исправил дефект , генерация id нужна была

2023-09-29 19:23 UTC, bezvrednyy commented on src/App.jsx
> +        });
Принимается. Но не совсем. Посмотри на два варианта и выбери тот, который проще понимается. Если бы было в одну строчку, для меня был бы действительно метод ниндзя. А так сильно понятне.

Если тебя смущает однобуквенная переменная "x", то в небольших циклах принято использовать её, т.к. уже понятно, что это фигура, ведь ты пробегаешь по массиву `figures`.

2023-09-29 19:32 UTC, bezvrednyy requested changes

2023-09-29 19:32 UTC, bezvrednyy commented on src/components/AppMenu.jsx
> +            value={fillColor || '#353535'}
Вижу магический цвет, который при этом используется в других компонентах. Магические цифры/строки, которые используется в нескольких местах логично вынести в единую **глобальную** константу, аля `export const DEFAULT_FIGURE_COLOR = '#353535'`

2023-09-29 19:32 UTC, bezvrednyy commented on src/components/Workspace.jsx
> +      !e.target.classList.contains('triangleContainer');
А нельзя сделать `const isClickOutside = e.target.classList.contains('workspace')`?

2023-09-30 07:20 UTC, GitMozzarella commented on src/components/AppMenu.jsx
> +            value={fillColor || '#353535'}
👍

2023-09-30 07:21 UTC, GitMozzarella commented on src/components/Workspace.jsx
> +      !e.target.classList.contains('triangleContainer');
👍

2024-01-17 15:12 UTC, closed without merging